### PR TITLE
create main screen

### PR DESCRIPTION
**Pull request by VoLy**
Create main screen
https://edu-redmine.framgia.vn/issues/270

### CODE REVIEW

**Comment by VoLy** [comment]
ready

**Comment by VoLy** [comment]
ready

**Comment by VoLy** [comment]
ready

**Comment by VoLy** [comment]
ready

**Comment by VoLy** [comment]
ready

**Comment by DoanVanToan** [comment]
commented

**Comment by VoLy** [comment]
ready

**Comment by DoanVanToan** [comment]
commented

**Comment by VoLy** [comment]
ready

**Comment by DoanVanToan** [comment]
commented

**Comment by VoLy** [comment]
ready

**Comment by VoLy** [comment]
ready

**Pull request merged**
